### ISSUE TITLE
Integration tests for Coinbase

### ISSUE THREAD

**Issue by straumat** [cassandre-tech/cassandre-trading-bot#30]

**Comment by G-MoneyTrading** [comment]
I think CoinbasePro has a bug. If I use coinbasepro as my exchange I get: Impossible to find the exchange you requested : coinbasepro. If I use kucoin it fails with a http 401 error. Not unexpected as I have absolutely no credentials there. kucoin does not fail with an unknown exchange. 

The error in eclipse reads as follows on attempting to run a test with coinbase or coinbasepro. Both are definately in xchange so they should work.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.593 s <<< FAILURE! - in com.G_MoneyTrading.app.javabot.SimpleStrategyTest
[ERROR] receivedData  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tech.cassandre.trading.bot.configuration.ExchangeAutoConfiguration': Invocation of init method failed; nested exception is tech.cassandre.trading.bot.util.exception.ConfigurationException: Impossible to find the exchange you requested : coinbasepro
Caused by: tech.cassandre.trading.bot.util.exception.ConfigurationException: Impossible to find the exchange you requested : coinbasepro

**Comment by G-MoneyTrading** [comment]
It seems I missed in every place you listed exchanges this works with and offered anything other then kucoin where you talked about adding the required dependency. I guess it's not really a bug in the program or code so much as a bug in the documentation. If as is it only works with kucoin possibly own that. 


Parameter | Description
-- | --
cassandre.trading.bot.exchange.name | Name of the exchange you want to access to. You can find a full list here

Page: https://trading-bot.cassandre.tech/project/source-code/exchange-configuration

Makes it sound like you put in the name as it is on the list and it should work. obviously it doesn't actually pull all those exhanges so I spent about a day looking into why the bean wasn't being created. Most results indicated inconsistent spring boot versions and one listed unknown dependencies. I wish I had that suggested earlier or had the foresight to check the dependencies for the actual exchange rather then the tech.cassandre.trading.bot.configuration.ExchangeAutoConfiigure.I don't know why I didn't look to see if coinbase, coinbase pro or kracken actually are dependencies according to cassandre-trading-bot. They are listed all over the documentation and likely are planned at some point but they obviously aren't ready yet. Possibly add to "Name of the exchange you want to access to. You can find the full list here." either a link to adding the required dependency so it would actually work or state "Only kucoin is supported at this time." Now to find the file with the maven dependencies so I can add coinbasepro and maybe get a semi-successful compile.

**Comment by straumat** [comment]
You are right, I will fix the documentation.
I only added to Cassandre the XChange library I fully tested and for the moment, I only finished Kucoin.

**Comment by straumat** [comment]
Closed because it seems it's not necessary thanks to XChange tests
