### ISSUE TITLE
Bot does work correct with multiple currencies

### ISSUE THREAD

**Issue by Tempys** [cassandre-tech/cassandre-trading-bot#556]
i have cashed 255 currencies in result of that code 
```
Set<CurrencyPairDTO> currencies =  exchangeService.getAvailableCurrencyPairs().stream()
                            .filter(i -> i.getQuoteCurrency().getCurrencyCode().equals("USDT"))
                            .peek(System.out::println)
                            .collect(Collectors.toSet());
```
but when i started bot i see only the next logs 

```
21:38:44 - Started Application in 21.649 seconds (JVM running for 22.538)
21:38:44 - OrderFlux - 0 order(s) updated
21:38:44 - TradeFlux - Retrieving new values
21:38:44 - TradeService - Getting trades from exchange

```

**Comment by straumat** [comment]
The problem comes from [ScheduleAutoConfiguration](https://github.com/cassandre-tech/cassandre-trading-bot/blob/development/spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/configuration/ScheduleAutoConfiguration.java). In fact, I did not set a thread pool. Line 74 is commented.

So basically, there is only one thread for the three schedulers (accounts, tickers, orders).
So account is retrieved, then a ticker is retrieved and then trades are retrieved. And this is the problem. For Binance, I call getTrades on the server for all the currency pairs... and only when all call will be made to getTrade on Binance for all currency pairs, tickers will be retrieved again.

By setting `scheduler.setPoolSize(3);` getTickers on Binance is being called during the calls to getTrades, real multi thread.

I'm fixing it but it breaks some of my other unit tests. I plan to fix all tomorrow
