### ISSUE TITLE
Question: Is there an easy way cassandre provided for maintaining order's state automatically?

### ISSUE THREAD

**Issue by huahouye** [cassandre-tech/cassandre-trading-bot#739]
**Is your feature request related to a problem? Please describe.**

I found cassandre created order and set that order's state to `PENDING_NEW`, then `OrderFlux` changed that order's state from `PENDING_NEW` to `NEW`, But that order's state wouldn't be updated to compeleted automatically even thought that order was already completed . Is there an easy way cassandre provided for maintaining order's state automatically? Or did I miss something here?

**Comment by straumat** [comment]
There are three steps:
- When Cassandre creates an order, we only have the order number, but we need to save the order in the database to link it to the strategy, so we create a local order with the status PENDING_NEW.
- OrderFlux will later ask for orders from the exchange, and usually, XChange will return the order from the exchange with the status NEW.
- The order could move to another status if we receive new data from the exchange in orderFlux but it depeds on exchange.
- That's why I don't rely on status in my code but I check isFullfilled method on order.

**Comment by huahouye** [comment]
@straumat yes, and I use `isFullfilled` in my business logic code. I want to show orders on webpage, but the state is incorrect. So I have to implement this by myself so far. And you make it more clear. Thanks.

**Comment by straumat** [comment]
@huahouye i think i should not only call openOrders to retrieve order but others methods even if they are not implemented on some exchange (like kucoin)

**Comment by huahouye** [comment]
@straumat OrderFlux calling openOrders is reasonable. You are right. I have better implement my own version getOrder. a for loop can handle it, it is not so hard.
